---
- name: Spin up Cent instance
  hosts: localhost
  gather_facts: false

  tasks:
  - name: search for the latest rhel 7 ami
    ec2_ami_find:
      owner: 410186602215
      region: "{{ region }}"
      name: CentOS Linux 7 x86_64 HVM EBS*
    register: find_results

  - debug:
      var: find_results.results[0].ami_id

  - name: Create instance
    ec2:
      key_name: "{{ keyz }}"
      group: servers
      volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: 28
        delete_on_termination: true
      vpc_subnet_id: "{{ which_subnet }}"
      instance_type: t2.micro
      image: "{{ find_results.results[0].ami_id }}"
      wait: true
      region: "{{ region }}"
      exact_count: 1
      count_tag:
        Count: oboy
      instance_tags:
        Name: "{{ project_name }}"
        Count: "{{ project_name }}"
      assign_public_ip: true
    register: ec2
